import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  icons: "/icon-192x192.png",
};

const ToastContainer = dynamic(() => import("@/components/Toast"), {
  ssr: false,
});

const ClientProvider = dynamic(() => import("@/components/ClientProvider"), { ssr: false })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer>
          <ClientProvider>{children}</ClientProvider>
        </ToastContainer>
      </body>
    </html>
  );
}
